import { Conflict } from "@/types";

export const conflictsData: Conflict[] = [
  {
    id: "c001",
    name: "Russia-Ukraine War",
    location: "Eastern Ukraine / Zaporizhzhia Front",
    country: "Ukraine",
    region: "Europe",
    type: "War",
    intensity: "CRITICAL",
    parties: ["Russian Armed Forces", "Ukrainian Armed Forces"],
    startDate: "2022-02-24",
    estimatedCasualties: 620000,
    escalationRisk: 78,
    latestDevelopment: "Ukrainian drone strike hits Saratov oil refinery. Russia launches 140-missile barrage on Kyiv energy grid.",
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    coordinates: [37.5, 48.5],
    externalActors: ["NATO", "USA", "UK", "France", "Germany", "Iran (Russia supplier)", "North Korea (ammunition)"],
  },
  {
    id: "c002",
    name: "Gaza-Israel Conflict",
    location: "Gaza Strip / West Bank",
    country: "Israel / Palestine",
    region: "Middle East",
    type: "War",
    intensity: "CRITICAL",
    parties: ["IDF", "Hamas", "Palestinian Islamic Jihad", "Hezbollah (Lebanon front)"],
    startDate: "2023-10-07",
    estimatedCasualties: 47000,
    escalationRisk: 82,
    latestDevelopment: "IDF expands Rafah ground operation. Hezbollah exchanges escalate on Lebanon border. Arab League emergency session called.",
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    coordinates: [34.4, 31.5],
    externalActors: ["USA", "Iran", "Qatar (mediator)", "Egypt (mediator)", "Houthis (Yemen)"],
  },
  {
    id: "c003",
    name: "Sudan Civil War",
    location: "Khartoum / Darfur / El Fasher",
    country: "Sudan",
    region: "Africa",
    type: "Civil War",
    intensity: "CRITICAL",
    parties: ["Sudanese Armed Forces (SAF)", "Rapid Support Forces (RSF)"],
    startDate: "2023-04-15",
    estimatedCasualties: 28000,
    escalationRisk: 71,
    latestDevelopment: "RSF captures North Darfur capital El Fasher. UN declares famine conditions. 8.6M internally displaced.",
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    coordinates: [32.5, 15.5],
    externalActors: ["UAE (RSF support alleged)", "Russia (Wagner/Africa Corps)", "Egypt (SAF support)", "Chad"],
  },
  {
    id: "c004",
    name: "Myanmar Civil War",
    location: "Shan State / Rakhine State / Sagaing",
    country: "Myanmar",
    region: "Asia-Pacific",
    type: "Civil War",
    intensity: "HIGH",
    parties: ["Myanmar Military (Tatmadaw)", "National Unity Government PDFs", "Three Brotherhood Alliance", "ARSA"],
    startDate: "2021-02-01",
    estimatedCasualties: 50000,
    escalationRisk: 58,
    latestDevelopment: "Brotherhood Alliance controls 70% of Shan State. Junta loses Laukkaing to MNDAA. China mediates ceasefire talks.",
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    coordinates: [96.5, 19.5],
    externalActors: ["China (junta support)", "India (border concerns)", "Thailand (humanitarian)"],
  },
  {
    id: "c005",
    name: "South China Sea Tensions",
    location: "Second Thomas Shoal / Scarborough Shoal",
    country: "Philippines / China",
    region: "Asia-Pacific",
    type: "Border Dispute",
    intensity: "HIGH",
    parties: ["PLA Navy / China Coast Guard", "Philippine Coast Guard / BRP Sierra Madre"],
    startDate: "2023-02-01",
    estimatedCasualties: 0,
    escalationRisk: 74,
    latestDevelopment: "Chinese water cannon disables Philippine resupply vessel. US-Philippine Mutual Defense Treaty invocation under review.",
    timestamp: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    coordinates: [118.0, 14.0],
    externalActors: ["USA", "Australia", "Japan", "Vietnam"],
  },
  {
    id: "c006",
    name: "Sahel Jihadist Insurgency",
    location: "Mali / Burkina Faso / Niger tri-border",
    country: "Multiple",
    region: "Africa",
    type: "Insurgency",
    intensity: "HIGH",
    parties: ["JNIM (al-Qaeda affiliate)", "ISGS (ISIS Sahel)", "Malian Armed Forces", "Wagner/Africa Corps", "FAMA"],
    startDate: "2012-01-01",
    estimatedCasualties: 40000,
    escalationRisk: 62,
    latestDevelopment: "JNIM seizes key Malian gold corridor. Alliance of Sahel States military drills. France fully expelled from region.",
    timestamp: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    coordinates: [-1.5, 14.0],
    externalActors: ["Russia (Wagner)", "Wagner Group", "EU (withdrawn)", "France (withdrawn)"],
  },
  {
    id: "c007",
    name: "Taiwan Strait Tensions",
    location: "Taiwan Strait / ADIZ violations",
    country: "Taiwan / China",
    region: "Asia-Pacific",
    type: "Border Dispute",
    intensity: "HIGH",
    parties: ["PLA Air Force", "PLA Eastern Theater Command", "Republic of China Armed Forces"],
    startDate: "2022-08-01",
    estimatedCasualties: 0,
    escalationRisk: 69,
    latestDevelopment: "PLA conducts largest ADIZ incursion — 91 aircraft. US carrier group Roosevelt dispatched. G7 joint statement issued.",
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    coordinates: [120.5, 24.0],
    externalActors: ["USA", "Japan", "Australia", "Philippines"],
  },
  {
    id: "c008",
    name: "Haiti Gang Crisis",
    location: "Port-au-Prince / Artibonite",
    country: "Haiti",
    region: "Caribbean",
    type: "Insurgency",
    intensity: "CRITICAL",
    parties: ["Viv Ansanm Gang Coalition (Barbecue)", "Haitian National Police", "MAST (Kenyan-led force)"],
    startDate: "2024-02-29",
    estimatedCasualties: 5000,
    escalationRisk: 67,
    latestDevelopment: "Gang controls 85% of Port-au-Prince. Kenyan MSS force under-resourced. Presidential council fractured.",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    coordinates: [-72.3, 18.5],
    externalActors: ["Kenya (MSS leader)", "USA", "Canada", "CARICOM"],
  },
  {
    id: "c009",
    name: "Ethiopia-Eritrea Border Flashpoint",
    location: "Tigray / Eritrean Border",
    country: "Ethiopia",
    region: "Africa",
    type: "Border Dispute",
    intensity: "MEDIUM",
    parties: ["Ethiopian National Defense Forces", "Eritrean Defense Forces", "TPLF remnants"],
    startDate: "2024-06-01",
    estimatedCasualties: 800,
    escalationRisk: 44,
    latestDevelopment: "Border skirmishes resume in Badme triangle. AU mediation team deployed. Pretoria Agreement under strain.",
    timestamp: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    coordinates: [39.5, 14.5],
    externalActors: ["African Union", "USA", "EU"],
  },
  {
    id: "c010",
    name: "Kashmir Line of Control Violations",
    location: "LoC / Poonch-Rajouri Sector",
    country: "India / Pakistan",
    region: "Asia-Pacific",
    type: "Border Dispute",
    intensity: "HIGH",
    parties: ["Indian Army", "Pakistani Army", "Lashkar-e-Taiba militants"],
    startDate: "2019-08-05",
    estimatedCasualties: 350,
    escalationRisk: 57,
    latestDevelopment: "Cross-LoC artillery exchange kills 14. Pakistan army claims Indian incursion. Both nuclear powers on elevated alert.",
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    coordinates: [74.5, 33.5],
    externalActors: ["China (Pakistan ally)", "USA (mediator)", "UN observers"],
  },
];
