import { Deal } from "@/types";

export const dealsData: Deal[] = [
  {
    id: "d001",
    type: "M&A",
    title: "ExxonMobil acquires Pioneer Natural Resources stake in Permian Basin",
    parties: ["ExxonMobil", "Pioneer Natural Resources"],
    value: 64700,
    currency: "USD",
    country: "United States",
    region: "North America",
    sector: "Energy",
    status: "COMPLETED",
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    details: "Landmark deal consolidates Permian Basin dominance. Regulatory approved after 14-month review.",
    isHot: true,
  },
  {
    id: "d002",
    type: "Acquisition",
    title: "SABIC acquires 25% stake in Nigerian LNG Terminal",
    parties: ["SABIC", "Nigerian National Petroleum Corp", "Shell"],
    value: 4200,
    currency: "USD",
    country: "Nigeria",
    region: "Africa",
    sector: "Energy",
    status: "ANNOUNCED",
    timestamp: new Date(Date.now() - 1000 * 60 * 34).toISOString(),
    details: "Saudi petrochemical giant expands African LNG footprint. Deal subject to NNPC board approval.",
    isHot: true,
  },
  {
    id: "d003",
    type: "Joint Venture",
    title: "Vale & BHP form critical minerals JV for DRC Cobalt extraction",
    parties: ["Vale S.A.", "BHP Group", "Glencore"],
    value: 8900,
    currency: "USD",
    country: "DRC",
    region: "Africa",
    sector: "Mining",
    status: "PENDING",
    timestamp: new Date(Date.now() - 1000 * 60 * 87).toISOString(),
    details: "Tri-party JV targets 240,000 tonnes annually. EU critical minerals framework compliance included.",
  },
  {
    id: "d004",
    type: "Contract",
    title: "Lockheed Martin wins $22B USAF next-gen fighter contract",
    parties: ["Lockheed Martin", "US Air Force"],
    value: 22000,
    currency: "USD",
    country: "United States",
    region: "North America",
    sector: "Defense",
    status: "ANNOUNCED",
    timestamp: new Date(Date.now() - 1000 * 60 * 145).toISOString(),
    details: "F-22 successor program. Contract covers 200 aircraft over 15 years. Boeing and Northrop challenged.",
    isHot: true,
  },
  {
    id: "d005",
    type: "Bond",
    title: "Saudi Aramco issues $10B sovereign green bond",
    parties: ["Saudi Aramco", "Goldman Sachs", "JPMorgan", "Citigroup"],
    value: 10000,
    currency: "USD",
    country: "Saudi Arabia",
    region: "Middle East",
    sector: "Energy",
    status: "COMPLETED",
    timestamp: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    details: "Oversubscribed 4.2x. Proceeds fund CCS and hydrogen projects. 30-year maturity.",
  },
  {
    id: "d006",
    type: "M&A",
    title: "Mitsubishi UFJ acquires Morgan Stanley Asia operations",
    parties: ["Mitsubishi UFJ Financial Group", "Morgan Stanley"],
    value: 18500,
    currency: "USD",
    country: "Japan",
    region: "Asia-Pacific",
    sector: "Finance",
    status: "RUMORED",
    timestamp: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    details: "Sources indicate advanced discussions. Would create largest Asian investment bank. Both deny.",
    isHot: true,
  },
  {
    id: "d007",
    type: "Partnership",
    title: "Microsoft & G42 $1.5B AI infrastructure deal for Middle East",
    parties: ["Microsoft", "G42 (UAE)"],
    value: 1500,
    currency: "USD",
    country: "UAE",
    region: "Middle East",
    sector: "Technology",
    status: "COMPLETED",
    timestamp: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    details: "Establishes AI hyperscale data centers across 6 Middle East countries. US govt approved.",
  },
  {
    id: "d008",
    type: "Acquisition",
    title: "Rio Tinto bids for Arcadium Lithium — Chile assets included",
    parties: ["Rio Tinto", "Arcadium Lithium"],
    value: 6700,
    currency: "USD",
    country: "Chile",
    region: "South America",
    sector: "Mining",
    status: "COMPLETED",
    timestamp: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    details: "Secures lithium supply chain for EV battery manufacturers. Atacama salar access key asset.",
  },
  {
    id: "d009",
    type: "Contract",
    title: "Huawei wins $3.2B Africa 5G infrastructure deal — 18 nations",
    parties: ["Huawei", "African Union Telecoms"],
    value: 3200,
    currency: "USD",
    country: "Multiple",
    region: "Africa",
    sector: "Technology",
    status: "ANNOUNCED",
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    details: "Despite US pressure, 18 African nations sign framework. US Exim Bank counter-offer pending.",
    isHot: true,
  },
  {
    id: "d010",
    type: "M&A",
    title: "Reliance Industries acquires Walt Disney India stake",
    parties: ["Reliance Industries", "The Walt Disney Company"],
    value: 8500,
    currency: "USD",
    country: "India",
    region: "Asia-Pacific",
    sector: "Media",
    status: "COMPLETED",
    timestamp: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    details: "Creates India's largest media conglomerate. Combines JioCinema and Disney+ Hotstar.",
  },
  {
    id: "d011",
    type: "Loan",
    title: "IMF extends $15B emergency credit line to Pakistan",
    parties: ["IMF", "Pakistan Government", "World Bank"],
    value: 15000,
    currency: "USD",
    country: "Pakistan",
    region: "Asia-Pacific",
    sector: "Sovereign",
    status: "PENDING",
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    details: "Extended Fund Facility conditional on tax reform and energy subsidy cuts. Board votes Tuesday.",
    isHot: true,
  },
  {
    id: "d012",
    type: "Joint Venture",
    title: "CATL & Ford battery plant JV in Michigan — restructured",
    parties: ["CATL", "Ford Motor Company"],
    value: 3500,
    currency: "USD",
    country: "United States",
    region: "North America",
    sector: "Manufacturing",
    status: "PENDING",
    timestamp: new Date(Date.now() - 1000 * 60 * 900).toISOString(),
    details: "Revised structure limits CATL IP exposure following Congressional pressure. DOE review ongoing.",
  },
  {
    id: "d013",
    type: "Contract",
    title: "Raytheon wins Poland air defense contract — Patriot system",
    parties: ["Raytheon Technologies", "Polish Ministry of Defense"],
    value: 7800,
    currency: "USD",
    country: "Poland",
    region: "Europe",
    sector: "Defense",
    status: "COMPLETED",
    timestamp: new Date(Date.now() - 1000 * 60 * 1200).toISOString(),
    details: "Largest EU defense procurement since 2022. Includes 12 Patriot batteries and 20-year support.",
  },
  {
    id: "d014",
    type: "IPO",
    title: "Dubai Electricity & Water Authority secondary offering",
    parties: ["DEWA", "Emirates NBD Capital", "Goldman Sachs"],
    value: 4100,
    currency: "USD",
    country: "UAE",
    region: "Middle East",
    sector: "Utilities",
    status: "ANNOUNCED",
    timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    details: "Government selling 5% stake. Roadshow starts Monday. Institutional demand already significant.",
  },
  {
    id: "d015",
    type: "Acquisition",
    title: "BlackRock acquires Global Infrastructure Partners for $12.5B",
    parties: ["BlackRock", "Global Infrastructure Partners"],
    value: 12500,
    currency: "USD",
    country: "United States",
    region: "North America",
    sector: "Infrastructure",
    status: "COMPLETED",
    timestamp: new Date(Date.now() - 1000 * 60 * 1600).toISOString(),
    details: "Positions BlackRock as world's largest infrastructure investment manager with $170B AUM.",
    isHot: true,
  },
];
