import { Election } from "@/types";

export const electionsData: Election[] = [
  {
    id: "e001",
    country: "Iran",
    region: "Middle East",
    type: "Presidential",
    date: "2026-06-12",
    status: "UPCOMING",
    candidates: [
      { name: "Mohammad Bagher Qalibaf", party: "Islamic Revolutionary Guard Corps-aligned", polling: 34, change: +3 },
      { name: "Ali Larijani", party: "Conservative", polling: 28, change: -1 },
      { name: "Masoud Pezeshkian", party: "Reformist", polling: 22, change: +5 },
      { name: "Saeed Jalili", party: "Hardline Conservative", polling: 16, change: -2 },
    ],
    geopoliticalImpact: "CRITICAL",
    turnoutExpected: 42,
    notes: "Supreme Leader Khamenei health concerns add uncertainty. IRGC candidate favored. Nuclear deal implications critical.",
  },
  {
    id: "e002",
    country: "Germany",
    region: "Europe",
    type: "Parliamentary",
    date: "2026-09-26",
    status: "UPCOMING",
    candidates: [
      { name: "CDU/CSU (Friedrich Merz)", party: "Center-Right", polling: 32, change: +1 },
      { name: "AfD (Alice Weidel)", party: "Far-Right", polling: 21, change: +2 },
      { name: "SPD (Olaf Scholz)", party: "Center-Left", polling: 16, change: -3 },
      { name: "Greens (Robert Habeck)", party: "Green", polling: 14, change: -1 },
    ],
    geopoliticalImpact: "HIGH",
    turnoutExpected: 76,
    notes: "Grand coalition vs CDU-FDP scenario debated. AfD surge concerns EU leadership. NATO commitment central issue.",
  },
  {
    id: "e003",
    country: "South Korea",
    region: "Asia-Pacific",
    type: "Presidential",
    date: "2026-06-03",
    status: "UPCOMING",
    candidates: [
      { name: "Lee Jae-myung", party: "Democratic Party", polling: 41, change: +4 },
      { name: "Han Dong-hoon", party: "People Power Party", polling: 36, change: -2 },
      { name: "Ahn Cheol-soo", party: "Reform Party", polling: 12, change: +1 },
    ],
    geopoliticalImpact: "HIGH",
    turnoutExpected: 77,
    notes: "Post-Yoon impeachment election. US-Korea alliance posture, THAAD deployment, and North Korea policy central.",
  },
  {
    id: "e004",
    country: "Nigeria",
    region: "Africa",
    type: "Presidential",
    date: "2027-02-01",
    status: "UPCOMING",
    candidates: [
      { name: "Bola Tinubu (incumbent)", party: "APC", polling: 38, change: -6 },
      { name: "Peter Obi", party: "Labour Party", polling: 31, change: +8 },
      { name: "Atiku Abubakar", party: "PDP", polling: 21, change: -2 },
    ],
    geopoliticalImpact: "HIGH",
    turnoutExpected: 35,
    notes: "Naira devaluation and fuel subsidy removal dominate. Tinubu faces economic backlash. Youth vote critical factor.",
  },
  {
    id: "e005",
    country: "Indonesia",
    region: "Asia-Pacific",
    type: "Parliamentary",
    date: "2026-04-09",
    status: "COMPLETED",
    candidates: [
      { name: "Gerindra-Golkar Coalition", party: "Prabowo bloc", polling: 42, change: +5 },
      { name: "PDI-P (Megawati faction)", party: "Nationalist", polling: 19, change: -12 },
      { name: "PKS-PKB Coalition", party: "Islamic", polling: 24, change: +2 },
    ],
    winnerPrediction: "Gerindra-Golkar Coalition",
    geopoliticalImpact: "MEDIUM",
    turnoutExpected: 81,
    notes: "Prabowo government consolidates power. Downstream nickel processing policy continues. China investment welcomed.",
  },
  {
    id: "e006",
    country: "Venezuela",
    region: "South America",
    type: "Presidential",
    date: "2025-07-28",
    status: "COMPLETED",
    candidates: [
      { name: "Nicolás Maduro (incumbent)", party: "PSUV", polling: 31, change: -8 },
      { name: "Edmundo González", party: "Democratic Opposition", polling: 62, change: +15 },
    ],
    winnerPrediction: "DISPUTED — Maduro declared winner by CNE",
    geopoliticalImpact: "HIGH",
    notes: "International community disputes results. González claims victory. USA sanctions intensified. Regional migration continues.",
  },
  {
    id: "e007",
    country: "Turkey",
    region: "Europe",
    type: "Snap Election",
    date: "2026-11-01",
    status: "UPCOMING",
    candidates: [
      { name: "Ekrem İmamoğlu", party: "CHP (Opposition)", polling: 46, change: +9 },
      { name: "Recep Tayyip Erdoğan", party: "AKP", polling: 42, change: -5 },
    ],
    geopoliticalImpact: "HIGH",
    turnoutExpected: 82,
    notes: "Erdoğan calls snap election amid economic pressure. İmamoğlu arrest attempt backfired. NATO-Russia dynamic key issue.",
  },
  {
    id: "e008",
    country: "Brazil",
    region: "South America",
    type: "Presidential",
    date: "2026-10-04",
    status: "UPCOMING",
    candidates: [
      { name: "Lula da Silva (incumbent)", party: "PT", polling: 36, change: -4 },
      { name: "Jair Bolsonaro (if eligible)", party: "PL", polling: 34, change: +2 },
      { name: "Simone Tebet", party: "MDB", polling: 12, change: +3 },
    ],
    geopoliticalImpact: "HIGH",
    turnoutExpected: 79,
    notes: "Bolsonaro eligibility ruling pending. Amazon policy, fiscal deficit, and China trade relations central issues.",
  },
  {
    id: "e009",
    country: "India",
    region: "Asia-Pacific",
    type: "Regional",
    date: "2026-05-15",
    status: "ONGOING",
    candidates: [
      { name: "BJP", party: "Ruling Party", polling: 44, change: -3 },
      { name: "INDIA Alliance (Congress + SP)", party: "Opposition", polling: 38, change: +6 },
      { name: "Samajwadi Party", party: "Regional", polling: 14, change: +1 },
    ],
    geopoliticalImpact: "MEDIUM",
    turnoutExpected: 65,
    notes: "Uttar Pradesh and Bihar state elections. Bellwether for 2029 general. Hindu nationalist vs caste coalition dynamic.",
  },
  {
    id: "e010",
    country: "Mexico",
    region: "North America",
    type: "Referendum",
    date: "2026-06-01",
    status: "UPCOMING",
    candidates: [
      { name: "YES — Judicial Reform Ratification", party: "Morena / PVEM", polling: 54, change: -2 },
      { name: "NO — Constitutional Opposition", party: "PAN / PRI / PRD", polling: 38, change: +4 },
    ],
    geopoliticalImpact: "HIGH",
    notes: "Claudia Sheinbaum's judicial overhaul faces popular vote. US concerns over rule of law and USMCA implications.",
  },
];
