import { IntelligenceItem } from "@/types";

export const intelligenceData: IntelligenceItem[] = [
  {
    id: "i001",
    person: "Vladimir Putin",
    title: "President of Russia",
    country: "Russia",
    category: "DIPLOMATIC",
    eventType: "Meeting",
    content: "Putin met Xi Jinping for undisclosed 4-hour session in Beijing. No joint statement issued. Chinese state media coverage blocked. Energy payments mechanism and Ukraine endgame discussed per Kremlin sources.",
    timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
    significance: "CRITICAL",
    source: "Kremlin Watch / Reuters Intelligence Desk",
    relatedTo: ["Russia-Ukraine War", "China-Russia Energy Deals"],
  },
  {
    id: "i002",
    person: "Elon Musk",
    title: "CEO Tesla/SpaceX, DOGE Director",
    country: "United States",
    category: "BUSINESS",
    eventType: "Communication",
    content: "Musk privately signaled to DOGE team plans to monetize government data access for Grok AI training. Internal messages leaked to WSJ. White House denies arrangement. Tesla stock up 4.2% on AI synergy speculation.",
    timestamp: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
    significance: "CRITICAL",
    source: "WSJ / Bloomberg Intelligence",
    relatedTo: ["DOGE operations", "AI regulatory framework"],
  },
  {
    id: "i003",
    person: "Mohammed bin Salman",
    title: "Crown Prince, Prime Minister of Saudi Arabia",
    country: "Saudi Arabia",
    category: "DIPLOMATIC",
    eventType: "Dinner",
    content: "MBS hosted private dinner with Jamie Dimon (JPMorgan), Larry Fink (BlackRock), and Ray Dalio. Topics reportedly included $600B US-Saudi investment framework and PIF listing of Aramco tranche. No press.",
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    significance: "CRITICAL",
    source: "FT Middle East Desk / Saudi insider",
    relatedTo: ["PIF Investment Strategy", "US-Saudi Relations"],
  },
  {
    id: "i004",
    person: "Narendra Modi",
    title: "Prime Minister of India",
    country: "India",
    category: "DIPLOMATIC",
    eventType: "Phone Call",
    content: "Modi-Zelensky call lasted 90 minutes — longest since Ukraine war began. India offered to host peace summit in New Delhi. Modi signals India no longer neutral, seeks permanent UNSC seat support from West.",
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    significance: "NOTABLE",
    source: "MEA Press Release / diplomatic cable",
    relatedTo: ["Russia-Ukraine War", "India UNSC Bid"],
  },
  {
    id: "i005",
    person: "Xi Jinping",
    title: "President of China, General Secretary CCP",
    country: "China",
    category: "POLITICAL",
    eventType: "Meeting",
    content: "Xi convened emergency Politburo Standing Committee session on Taiwan after PLA ADIZ patrol provoked US carrier response. Three factions debated: hardliners push Q4 2026 blockade exercise; moderates urge economic pressure only.",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    significance: "CRITICAL",
    source: "Taiwan Security Bureau / signals intelligence",
    relatedTo: ["Taiwan Strait Tensions", "China-US Relations"],
  },
  {
    id: "i006",
    person: "Jamie Dimon",
    title: "CEO, JPMorgan Chase",
    country: "United States",
    category: "BUSINESS",
    eventType: "Statement",
    content: "Dimon told senior executives in internal town hall: 'We are preparing for a 7% 10-year yield scenario.' JPMorgan quietly reducing duration exposure. Warns staff of commercial real estate 'hurricane season' starting Q3.",
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    significance: "CRITICAL",
    source: "JPMorgan internal memo (leaked) / Bloomberg",
    relatedTo: ["US Treasury Market", "Commercial Real Estate Crisis"],
  },
  {
    id: "i007",
    person: "Volodymyr Zelensky",
    title: "President of Ukraine",
    country: "Ukraine",
    category: "MILITARY",
    eventType: "Visit",
    content: "Zelensky made unannounced visit to Zaporizhzhia front. Briefed on new NATO-supplied deep-strike capability. Authorized strikes 200km inside Russian territory. Discussed with commanders F-16 operational readiness.",
    timestamp: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    significance: "SENSITIVE",
    source: "Ukrainian Presidential Office / Axios",
    relatedTo: ["Russia-Ukraine War", "NATO Arms Supply"],
  },
  {
    id: "i008",
    person: "Janet Yellen",
    title: "Former US Treasury Secretary",
    country: "United States",
    category: "BUSINESS",
    eventType: "Statement",
    content: "Yellen privately told G7 finance ministers that US debt trajectory is 'unsustainable' without Congressional action. Warned dollar reserve currency status faces 15-year erosion horizon. Remarks not for public attribution.",
    timestamp: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    significance: "SENSITIVE",
    source: "G7 Finance Ministers meeting readout (leaked)",
    relatedTo: ["US Debt Crisis", "Dollar Reserve Currency"],
  },
  {
    id: "i009",
    person: "Recep Tayyip Erdoğan",
    title: "President of Turkey",
    country: "Turkey",
    category: "DIPLOMATIC",
    eventType: "Meeting",
    content: "Erdoğan met in Ankara with Iranian FM and Russian FM simultaneously — extraordinary trilateral. Turkey offering to be Ukraine-Russia 'final mediator.' Seeks removal from CAATSA sanctions as price for cooperation.",
    timestamp: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    significance: "CRITICAL",
    source: "Hurriyet / Anadolu Agency / diplomatic sources",
    relatedTo: ["Russia-Ukraine War", "Turkey NATO Relations"],
  },
  {
    id: "i010",
    person: "Bill Gates",
    title: "Co-chair, Bill & Melinda Gates Foundation",
    country: "United States",
    category: "PERSONAL",
    eventType: "Meeting",
    content: "Gates held private 3-day retreat with 12 global health ministers at his Washington state estate. Agenda: pandemic preparedness fund of $25B and MRNA manufacturing transfer to Africa. No media invited. WHO Director attended.",
    timestamp: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    significance: "NOTABLE",
    source: "Politico / Seattle Times investigative",
    relatedTo: ["Global Health Security", "WHO Pandemic Treaty"],
  },
  {
    id: "i011",
    person: "MBS (Mohammed bin Salman)",
    title: "Crown Prince, PM of Saudi Arabia",
    country: "Saudi Arabia",
    category: "PERSONAL",
    eventType: "Travel",
    content: "MBS made unannounced 48-hour trip to Beijing. Xi bypassed normal protocol with airport reception. Believed to include oil-for-yuan settlement framework expansion and sale of 1% Aramco stake to Chinese sovereign funds.",
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    significance: "CRITICAL",
    source: "Flight tracking / Saudi Gazette / SCMP",
    relatedTo: ["Petrodollar System", "China-Saudi Relations", "De-dollarization"],
  },
  {
    id: "i012",
    person: "Ursula von der Leyen",
    title: "President, European Commission",
    country: "Belgium / EU",
    category: "POLITICAL",
    eventType: "Statement",
    content: "Von der Leyen in closed-door EPP meeting stated EU ready to invoke Article 42(7) collective defense if Russia attacks Estonia or Latvia. Signaled European army proposal will be fast-tracked by 2027. Macron present.",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    significance: "CRITICAL",
    source: "EUobserver / European Parliament sources",
    relatedTo: ["Russia NATO Tensions", "EU Defense Integration"],
  },
  {
    id: "i013",
    person: "Warren Buffett",
    title: "CEO, Berkshire Hathaway",
    country: "United States",
    category: "BUSINESS",
    eventType: "Deal",
    content: "Buffett's Berkshire has been quietly buying Japanese trading houses beyond disclosed 8% stakes. Total exposure now believed to exceed $35B. Buffett confirmed '2026 will see biggest Berkshire acquisition in history' to board.",
    timestamp: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    significance: "SENSITIVE",
    source: "Japan FSA filings / WSJ Berkshire beat",
    relatedTo: ["Japanese Economy", "Berkshire Acquisition Strategy"],
  },
  {
    id: "i014",
    person: "Antonio Guterres",
    title: "UN Secretary-General",
    country: "Portugal / UN",
    category: "DIPLOMATIC",
    eventType: "Statement",
    content: "Guterres in private told UNSC members that UN is '12-18 months from insolvency' without emergency contributions. US arrears at $3.7B. Warned of collapse of peacekeeping missions in 6 countries simultaneously.",
    timestamp: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    significance: "SENSITIVE",
    source: "UN internal budget memo / Reuters",
    relatedTo: ["UN Funding Crisis", "Global Peacekeeping"],
  },
  {
    id: "i015",
    person: "Sam Altman",
    title: "CEO, OpenAI",
    country: "United States",
    category: "BUSINESS",
    eventType: "Meeting",
    content: "Altman met UAE President Sheikh Mohammed bin Zayed for second time in 30 days. UAE agreed to invest $10B in OpenAI data center expansion in Abu Dhabi. Separately, Altman lobbied NSC for AGI regulatory framework delay.",
    timestamp: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
    significance: "NOTABLE",
    source: "FT / Abu Dhabi Media Office",
    relatedTo: ["AI Global Governance", "UAE-US Tech Relations"],
  },
];
