import { MoneyMove } from "@/types";

export const moneyMovesData: MoneyMove[] = [
  {
    id: "m001",
    institution: "JPMorgan Chase",
    type: "BUY",
    asset: "Indian Government Bonds (10Y)",
    assetType: "Bond",
    valueMn: 2800,
    timestamp: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
    significance: "MAJOR",
    details: "JPMorgan adds INR bonds to EM index, triggering $2.8B passive inflow. India inclusion in GBI-EM Global index driving institutional demand.",
    country: "India",
    sector: "Sovereign Debt",
  },
  {
    id: "m002",
    institution: "Blackrock",
    type: "ACCUMULATE",
    asset: "Saudi Aramco",
    assetType: "Stock",
    valueMn: 4200,
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    significance: "MAJOR",
    details: "BlackRock increases Aramco stake ahead of Vision 2030 projects. Larry Fink met Crown Prince MBS privately in Riyadh.",
    country: "Saudi Arabia",
    sector: "Energy",
  },
  {
    id: "m003",
    institution: "Goldman Sachs",
    type: "SHORT",
    asset: "EUR/USD",
    assetType: "Currency",
    valueMn: 1800,
    timestamp: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
    significance: "NOTABLE",
    details: "Goldman opens EUR short, target 1.04. ECB-Fed rate differential widening expected. German recession concerns mount.",
    sector: "FX",
  },
  {
    id: "m004",
    institution: "Vanguard",
    type: "DIVEST",
    asset: "Chinese Tech ADRs (BABA, JD, BIDU)",
    assetType: "Stock",
    valueMn: 3600,
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    significance: "MAJOR",
    details: "Vanguard liquidates $3.6B in Chinese ADRs following PCAOB risk assessment. Accelerates Western institutional China exit.",
    country: "China",
    sector: "Technology",
  },
  {
    id: "m005",
    institution: "Bridgewater Associates",
    type: "BUY",
    asset: "Gold Futures (COMEX)",
    assetType: "Commodity",
    valueMn: 950,
    timestamp: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    significance: "NOTABLE",
    details: "Dalio's fund increases gold allocation to 20% of portfolio. Central bank buying and de-dollarization thesis cited.",
    sector: "Commodities",
  },
  {
    id: "m006",
    institution: "Norges Bank Investment Management",
    type: "BUY",
    asset: "Emerging Market Infrastructure",
    assetType: "Private Equity",
    valueMn: 7200,
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    significance: "MAJOR",
    details: "Norway's $1.7T sovereign fund allocates $7.2B to EM infrastructure. India, Brazil, Southeast Asia focus. Renewable energy priority.",
    sector: "Infrastructure",
  },
  {
    id: "m007",
    institution: "Citadel LLC",
    type: "SELL",
    asset: "US Treasuries (30Y)",
    assetType: "Bond",
    valueMn: 5500,
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    significance: "MAJOR",
    details: "Ken Griffin's Citadel dumps long-duration Treasuries. Fiscal deficit concerns and Fed higher-for-longer stance cited.",
    country: "United States",
    sector: "Sovereign Debt",
  },
  {
    id: "m008",
    institution: "Abu Dhabi Investment Authority",
    type: "BUY",
    asset: "Global Data Centers Portfolio",
    assetType: "Real Estate",
    valueMn: 6000,
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    significance: "MAJOR",
    details: "ADIA commits $6B to data center REIT strategy. AI infrastructure boom driving demand. US, Europe, Japan markets targeted.",
    sector: "Technology Infrastructure",
  },
  {
    id: "m009",
    institution: "Soros Fund Management",
    type: "SHORT",
    asset: "Turkish Lira / Bonds",
    assetType: "Currency",
    valueMn: 420,
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    significance: "NOTABLE",
    details: "Soros opens TRY short ahead of Turkish elections. Erdoğan economic model risks inflation relapse. Local investors hedging offshore.",
    country: "Turkey",
    sector: "EM Debt",
  },
  {
    id: "m010",
    institution: "JPMorgan Chase",
    type: "SELL",
    asset: "Russian Ruble-Denominated Assets",
    assetType: "Bond",
    valueMn: 890,
    timestamp: new Date(Date.now() - 1000 * 60 * 340).toISOString(),
    significance: "NOTABLE",
    details: "Continued wind-down of legacy Russian positions under OFAC license. Secondary market sales at significant discount.",
    country: "Russia",
    sector: "Sovereign Debt",
  },
  {
    id: "m011",
    institution: "Temasek Holdings",
    type: "ACCUMULATE",
    asset: "Southeast Asian AI Startups",
    assetType: "Private Equity",
    valueMn: 1800,
    timestamp: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
    significance: "NOTABLE",
    details: "Singapore sovereign fund targets AI unicorns in Singapore, Indonesia, Vietnam. $1.8B committed across 12 companies.",
    sector: "Technology",
  },
  {
    id: "m012",
    institution: "Saudi Public Investment Fund",
    type: "BUY",
    asset: "Lucid Motors & EV Supply Chain",
    assetType: "Stock",
    valueMn: 3100,
    timestamp: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    significance: "MAJOR",
    details: "PIF increases Lucid stake and invests in battery supply chain across Southeast Asia and Africa. Vision 2030 EV hub strategy.",
    sector: "Automotive",
  },
  {
    id: "m013",
    institution: "Goldman Sachs",
    type: "BUY",
    asset: "Copper Futures & Mining Equity",
    assetType: "Commodity",
    valueMn: 2200,
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    significance: "MAJOR",
    details: "Goldman upgrades copper to 'super-cycle' thesis. Energy transition demand + supply constraints = $15,000/t target by 2027.",
    sector: "Commodities",
  },
  {
    id: "m014",
    institution: "Fidelity International",
    type: "DIVEST",
    asset: "Commercial Real Estate (US)",
    assetType: "Real Estate",
    valueMn: 2900,
    timestamp: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    significance: "MAJOR",
    details: "Fidelity liquidates US office and retail CRE portfolio. Remote work structural shift and refinancing crisis forcing hand.",
    country: "United States",
    sector: "Real Estate",
  },
  {
    id: "m015",
    institution: "Caisse de dépôt (CDPQ)",
    type: "BUY",
    asset: "Indian Renewable Energy Infrastructure",
    assetType: "Private Equity",
    valueMn: 4500,
    timestamp: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    significance: "MAJOR",
    details: "Canada's CDPQ commits $4.5B to Indian solar and wind projects. Adani Green Energy and ReNew Power partnerships announced.",
    country: "India",
    sector: "Renewable Energy",
  },
];
