import { ResourceDiscovery } from "@/types";

export const resourcesData: ResourceDiscovery[] = [
  {
    id: "r001",
    resource: "Lithium",
    location: "Atacama Plateau, Sector 7",
    country: "Bolivia",
    coordinates: [-67.5, -19.5],
    estimatedValueBn: 2800,
    discoveredBy: "USGS / Bolivian Geological Survey",
    tenderStatus: "OPEN",
    applicants: ["Albemarle Corp", "SQM (Chile)", "CATL", "Ganfeng Lithium", "Rio Tinto", "Pilbara Minerals"],
    deadline: "2026-06-30",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    description: "Largest lithium brine deposit ever confirmed. 23 million tonnes estimated reserves. Bolivia has stipulated 51% state ownership minimum.",
  },
  {
    id: "r002",
    resource: "Oil",
    location: "Offshore Block 58, Suriname EEZ",
    country: "Suriname",
    coordinates: [-56.0, 6.5],
    estimatedValueBn: 750,
    discoveredBy: "TotalEnergies / APA Corporation",
    tenderStatus: "AWARDED",
    applicants: ["TotalEnergies", "APA Corporation", "Staatsolie (Suriname)"],
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    description: "4.8 billion barrels proven recoverable. Production start Q3 2026. Largest discovery in Americas since 2015.",
  },
  {
    id: "r003",
    resource: "Rare Earth",
    location: "Kvanefjeld, Southwest Greenland",
    country: "Greenland",
    coordinates: [-48.5, 60.0],
    estimatedValueBn: 1200,
    discoveredBy: "Greenland Minerals Ltd",
    tenderStatus: "OPEN",
    applicants: ["MP Materials (USA)", "Lynas (Australia)", "China Northern Rare Earth", "REE Automotive", "Vital Metals"],
    deadline: "2026-08-15",
    timestamp: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    description: "World's 2nd largest rare earth deposit. Contains neodymium, dysprosium critical for EV motors. US-China bidding war expected.",
  },
  {
    id: "r004",
    resource: "Cobalt",
    location: "Lualaba Province, Manono",
    country: "DRC",
    coordinates: [26.5, -7.0],
    estimatedValueBn: 540,
    discoveredBy: "AVZ Minerals / DRC Geological Institute",
    tenderStatus: "UPCOMING",
    applicants: ["Glencore", "Vale", "BHP", "Zhejiang Huayou Cobalt", "Freeport-McMoRan"],
    deadline: "2026-09-01",
    timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    description: "High-grade cobalt-lithium deposit. 2.7M tonnes cobalt equivalent. Political risk flagged by World Bank.",
  },
  {
    id: "r005",
    resource: "Gas",
    location: "Rovuma Basin Block 4, Offshore",
    country: "Mozambique",
    coordinates: [40.5, -11.5],
    estimatedValueBn: 890,
    discoveredBy: "ENI / ExxonMobil",
    tenderStatus: "OPEN",
    applicants: ["ENI", "ExxonMobil", "TotalEnergies", "Shell", "CNPC", "KOGAS (South Korea)"],
    deadline: "2026-05-30",
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    description: "65 TCF proven gas reserves. New block adjacent to producing Coral FLNG. Security concerns from Cabo Delgado insurgency.",
  },
  {
    id: "r006",
    resource: "Gold",
    location: "Murmansk Oblast Deep Seam",
    country: "Russia",
    coordinates: [33.0, 68.5],
    estimatedValueBn: 320,
    discoveredBy: "Polyus Gold / Russian Federal Geological Agency",
    tenderStatus: "CLOSED",
    applicants: ["Polyus Gold (Russia)", "Severstal Group"],
    timestamp: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    description: "Western sanctions limit international participation. Russian domestic tender only. 8,000 tonnes estimated reserves.",
  },
  {
    id: "r007",
    resource: "Copper",
    location: "Pebble Deposit, Bristol Bay, Alaska",
    country: "United States",
    coordinates: [-158.5, 59.8],
    estimatedValueBn: 680,
    discoveredBy: "Northern Dynasty Minerals",
    tenderStatus: "UPCOMING",
    applicants: ["Rio Tinto", "First Quantum Minerals", "Freeport-McMoRan", "Antofagasta PLC"],
    deadline: "2026-10-15",
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    description: "World's largest undeveloped copper-gold deposit. EPA injunction lifted. Environmental opposition from tribal groups ongoing.",
  },
  {
    id: "r008",
    resource: "Uranium",
    location: "Tim Mersoi Basin, Agadez",
    country: "Niger",
    coordinates: [8.5, 17.5],
    estimatedValueBn: 410,
    discoveredBy: "IAEA / Orano (France)",
    tenderStatus: "OPEN",
    applicants: ["Orano SA (France)", "Kazatomprom", "Uranium One (Russia)", "Cameco (Canada)"],
    deadline: "2026-07-01",
    timestamp: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    description: "Post-junta tender re-opening. French operator expelled, replaced by open bidding. Strategic asset in global nuclear energy revival.",
  },
  {
    id: "r009",
    resource: "Nickel",
    location: "Raja Ampat Deep Deposit, Papua",
    country: "Indonesia",
    coordinates: [130.5, -1.0],
    estimatedValueBn: 560,
    discoveredBy: "Vale Indonesia / MIND ID",
    tenderStatus: "AWARDED",
    applicants: ["Vale Indonesia", "Tsingshan Holding (China)", "Harita Nickel"],
    timestamp: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    description: "Indonesia continues downstream processing mandate. Only domestically-smelted nickel eligible for export. HPAL plant required.",
  },
  {
    id: "r010",
    resource: "Phosphate",
    location: "Western Sahara Bou Craa, Basin Extension",
    country: "Morocco",
    coordinates: [-14.5, 26.5],
    estimatedValueBn: 1800,
    discoveredBy: "OCP Group (Morocco)",
    tenderStatus: "CLOSED",
    applicants: ["OCP Group", "Mosaic Company"],
    timestamp: new Date(Date.now() - 1000 * 60 * 900).toISOString(),
    description: "New extension adds 30% to known reserves. Critical for global food security. UN status of Western Sahara adds political complexity.",
  },
  {
    id: "r011",
    resource: "Oil",
    location: "Namibe Basin, Offshore Block 30",
    country: "Angola",
    coordinates: [11.5, -14.5],
    estimatedValueBn: 420,
    discoveredBy: "TotalEnergies / Sonangol",
    tenderStatus: "UPCOMING",
    applicants: ["TotalEnergies", "Equinor", "BP", "Chevron", "CNOOC"],
    deadline: "2026-06-15",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    description: "Pre-salt formation similar to Brazilian Santos Basin. 3.1 billion barrels potential. Deepwater 2,800m depth.",
  },
];
